import { pgTable, text, timestamp, boolean, varchar, integer, index, uniqueIndex } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// --- BetterAuth Required Schema ---
export const users = pgTable("user", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").notNull().unique(),
	emailVerified: boolean("emailVerified").notNull(),
	image: text("image"),
	createdAt: timestamp("createdAt").notNull(),
	updatedAt: timestamp("updatedAt").notNull()
});

export const sessions = pgTable("session", {
	id: text("id").primaryKey(),
	expiresAt: timestamp("expiresAt").notNull(),
	ipAddress: text("ipAddress"),
	userAgent: text("userAgent"),
	userId: text("userId").notNull().references(() => users.id)
});

export const accounts = pgTable("account", {
	id: text("id").primaryKey(),
	accountId: text("accountId").notNull(),
	providerId: text("providerId").notNull(),
	userId: text("userId").notNull().references(() => users.id),
	accessToken: text("accessToken"),
	refreshToken: text("refreshToken"),
	idToken: text("idToken"),
	expiresAt: timestamp("expiresAt"),
	password: text("password")
});

// --- NewsGate Specific Schema ---

export const sources = pgTable("source", {
	id: text("id").primaryKey(), // e.g. "cnn-indonesia", "kompas"
	name: varchar("name", { length: 255 }).notNull(),
	baseUrl: varchar("base_url", { length: 255 }).notNull(),
	iconUrl: text("icon_url"),
	createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Enum for categories to ensure consistency
export type Category = "politik" | "ekonomi" | "teknologi" | "olahraga" | "hiburan" | "kesehatan";

export const newsArticles = pgTable("news_article", {
	id: text("id").primaryKey(), // UUID generated by app
	title: text("title").notNull(),
	slug: varchar("slug", { length: 500 }).notNull().unique(),
	content: text("content"), // Snippet or full content
	sourceUrl: text("source_url").notNull().unique(), // Important for deduplication
	imageUrl: text("image_url"),
	category: varchar("category", { length: 100 }).notNull(), // Map to Category enum
	sentimentScore: integer("sentiment_score"), // e.g. 1 to 100, or -1 (negative), 0, 1 (positive)
	sourceId: text("source_id").notNull().references(() => sources.id),
	publishedAt: timestamp("published_at").notNull(),
	createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
	return {
		categoryIdx: index("article_category_idx").on(table.category),
		publishedAtIdx: index("article_published_at_idx").on(table.publishedAt),
	};
});

export const userPreferences = pgTable("user_preference", {
	id: text("id").primaryKey(),
	userId: text("user_id").notNull().references(() => users.id, { onDelete: 'cascade' }),
	category: varchar("category", { length: 100 }).notNull(),
	createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
    return {
        userCatUnique: uniqueIndex("user_category_unique_idx").on(table.userId, table.category)
    }
});

// --- Relations ---

export const sourcesRelations = relations(sources, ({ many }) => ({
	articles: many(newsArticles),
}));

export const newsArticlesRelations = relations(newsArticles, ({ one }) => ({
	source: one(sources, {
		fields: [newsArticles.sourceId],
		references: [sources.id],
	}),
}));

export const usersRelations = relations(users, ({ many }) => ({
	preferences: many(userPreferences),
}));
